-- Seed data generated from data/seed-resources.ts.
-- Run supabase/schema.sql first.

begin;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('codex-skill-openai-docs', 'Codex Skill: OpenAI Docs', 'agent_skill', 'Guides Codex toward official OpenAI product and API documentation when building with OpenAI models, tools, and Codex surfaces.', array['Codex']::text[], 'Built-in skill: openai-docs', array['OpenAI API integration', 'model selection', 'Codex workflow guidance']::text[], 'low', 94, 92, 'https://platform.openai.com/docs', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('codex', 'codex', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-openai-docs' and tags.slug = 'codex' on conflict do nothing;
insert into public.tags (slug, name, category) values ('openai', 'openai', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-openai-docs' and tags.slug = 'openai' on conflict do nothing;
insert into public.tags (slug, name, category) values ('docs', 'docs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-openai-docs' and tags.slug = 'docs' on conflict do nothing;
insert into public.tags (slug, name, category) values ('api', 'api', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-openai-docs' and tags.slug = 'api' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('codex-skill-github-pr-review', 'Codex Skill: GitHub PR Review', 'agent_skill', 'Helps inspect GitHub pull requests, review comments, CI state, and repository context before implementing fixes.', array['Codex']::text[], 'Built-in GitHub skill set', array['PR review', 'CI debugging', 'review comment resolution']::text[], 'low', 91, 88, 'https://github.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('codex', 'codex', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-github-pr-review' and tags.slug = 'codex' on conflict do nothing;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-github-pr-review' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('pull-request', 'pull-request', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-github-pr-review' and tags.slug = 'pull-request' on conflict do nothing;
insert into public.tags (slug, name, category) values ('review', 'review', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-github-pr-review' and tags.slug = 'review' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('codex-skill-skill-creator', 'Codex Skill: Skill Creator', 'agent_skill', 'Provides a structured workflow for creating new reusable Codex skills with instructions, examples, and operating rules.', array['Codex']::text[], 'Built-in skill: skill-creator', array['Create internal skills', 'document workflows', 'standardize agent behavior']::text[], 'low', 90, 90, 'https://developers.openai.com/codex', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('codex', 'codex', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-skill-creator' and tags.slug = 'codex' on conflict do nothing;
insert into public.tags (slug, name, category) values ('skills', 'skills', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-skill-creator' and tags.slug = 'skills' on conflict do nothing;
insert into public.tags (slug, name, category) values ('automation', 'automation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-skill-creator' and tags.slug = 'automation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('knowledge', 'knowledge', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-skill-creator' and tags.slug = 'knowledge' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('codex-skill-browser-control', 'Codex Skill: Browser Control', 'agent_skill', 'Controls an in-app browser for local verification, screenshots, route testing, and UI inspection.', array['Codex']::text[], 'Built-in browser plugin skill', array['Visual QA', 'localhost testing', 'interactive UI verification']::text[], 'medium', 86, 85, 'https://developers.openai.com/codex', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('codex', 'codex', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-browser-control' and tags.slug = 'codex' on conflict do nothing;
insert into public.tags (slug, name, category) values ('browser', 'browser', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-browser-control' and tags.slug = 'browser' on conflict do nothing;
insert into public.tags (slug, name, category) values ('testing', 'testing', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-browser-control' and tags.slug = 'testing' on conflict do nothing;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'codex-skill-browser-control' and tags.slug = 'ui' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('claude-skills', 'Claude Skills', 'agent_skill', 'Reusable instructions and domain procedures for Claude-based workflows, useful as reference material for cross-agent skill design.', array['Claude', 'Codex']::text[], 'Add skill instructions to the target agent workspace', array['Cross-agent workflow design', 'prompt operating procedures', 'team playbooks']::text[], 'medium', 82, 80, 'https://docs.anthropic.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('claude', 'claude', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'claude-skills' and tags.slug = 'claude' on conflict do nothing;
insert into public.tags (slug, name, category) values ('skills', 'skills', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'claude-skills' and tags.slug = 'skills' on conflict do nothing;
insert into public.tags (slug, name, category) values ('agents', 'agents', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'claude-skills' and tags.slug = 'agents' on conflict do nothing;
insert into public.tags (slug, name, category) values ('workflow', 'workflow', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'claude-skills' and tags.slug = 'workflow' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-github', 'MCP Server: GitHub', 'mcp_server', 'Connects agents to GitHub repositories, issues, pull requests, review comments, and code collaboration workflows.', array['Codex', 'Claude', 'Cursor']::text[], 'Configure GitHub MCP server with a GitHub token', array['Repository inspection', 'issue triage', 'PR automation']::text[], 'medium', 90, 91, 'https://github.com/github/github-mcp-server', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-github' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-github' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('repo', 'repo', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-github' and tags.slug = 'repo' on conflict do nothing;
insert into public.tags (slug, name, category) values ('issues', 'issues', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-github' and tags.slug = 'issues' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-playwright', 'MCP Server: Playwright', 'mcp_server', 'Gives agents browser automation capabilities for navigation, screenshots, form filling, and web UI validation.', array['Codex', 'Claude', 'Cursor']::text[], 'npx @playwright/mcp', array['End-to-end testing', 'visual inspection', 'browser automation']::text[], 'medium', 88, 87, 'https://github.com/microsoft/playwright-mcp', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-playwright' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('playwright', 'playwright', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-playwright' and tags.slug = 'playwright' on conflict do nothing;
insert into public.tags (slug, name, category) values ('browser', 'browser', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-playwright' and tags.slug = 'browser' on conflict do nothing;
insert into public.tags (slug, name, category) values ('testing', 'testing', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-playwright' and tags.slug = 'testing' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-firecrawl', 'MCP Server: Firecrawl', 'mcp_server', 'Enables agents to crawl, scrape, and convert websites into structured markdown or data for downstream reasoning.', array['Codex', 'Claude', 'Cursor']::text[], 'npx -y firecrawl-mcp', array['Website ingestion', 'research collection', 'content extraction']::text[], 'medium', 82, 84, 'https://github.com/mendableai/firecrawl-mcp-server', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-firecrawl' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('firecrawl', 'firecrawl', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-firecrawl' and tags.slug = 'firecrawl' on conflict do nothing;
insert into public.tags (slug, name, category) values ('scraping', 'scraping', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-firecrawl' and tags.slug = 'scraping' on conflict do nothing;
insert into public.tags (slug, name, category) values ('research', 'research', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-firecrawl' and tags.slug = 'research' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-supabase', 'MCP Server: Supabase', 'mcp_server', 'Lets agents inspect and operate Supabase projects, database schema, SQL, auth, and backend resources.', array['Codex', 'Claude', 'Cursor']::text[], 'Configure Supabase MCP with project credentials', array['Schema inspection', 'SQL generation', 'backend integration']::text[], 'medium', 87, 89, 'https://github.com/supabase-community/supabase-mcp', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-supabase' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('supabase', 'supabase', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-supabase' and tags.slug = 'supabase' on conflict do nothing;
insert into public.tags (slug, name, category) values ('postgres', 'postgres', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-supabase' and tags.slug = 'postgres' on conflict do nothing;
insert into public.tags (slug, name, category) values ('database', 'database', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-supabase' and tags.slug = 'database' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-context7', 'MCP Server: Context7', 'mcp_server', 'Provides agents with current library documentation and code examples for framework-aware implementation.', array['Codex', 'Claude', 'Cursor']::text[], 'npx -y @upstash/context7-mcp', array['Library docs lookup', 'API usage examples', 'implementation guidance']::text[], 'low', 88, 90, 'https://github.com/upstash/context7', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-context7' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('docs', 'docs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-context7' and tags.slug = 'docs' on conflict do nothing;
insert into public.tags (slug, name, category) values ('context7', 'context7', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-context7' and tags.slug = 'context7' on conflict do nothing;
insert into public.tags (slug, name, category) values ('libraries', 'libraries', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-context7' and tags.slug = 'libraries' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-filesystem', 'MCP Server: Filesystem', 'mcp_server', 'Allows agents to read and write explicitly allowed local files through a controlled MCP filesystem surface.', array['Codex', 'Claude', 'Cursor']::text[], 'npx -y @modelcontextprotocol/server-filesystem <path>', array['Local project edits', 'file inspection', 'workspace automation']::text[], 'high', 76, 80, 'https://github.com/modelcontextprotocol/servers', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-filesystem' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('filesystem', 'filesystem', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-filesystem' and tags.slug = 'filesystem' on conflict do nothing;
insert into public.tags (slug, name, category) values ('local', 'local', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-filesystem' and tags.slug = 'local' on conflict do nothing;
insert into public.tags (slug, name, category) values ('workspace', 'workspace', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-filesystem' and tags.slug = 'workspace' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('mcp-server-memory', 'MCP Server: Memory', 'mcp_server', 'Stores durable knowledge graph style memory for agents that need persistent user or project context.', array['Claude', 'Cursor', 'Codex']::text[], 'npx -y @modelcontextprotocol/server-memory', array['Persistent context', 'user preferences', 'project knowledge']::text[], 'medium', 78, 76, 'https://github.com/modelcontextprotocol/servers', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('mcp', 'mcp', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-memory' and tags.slug = 'mcp' on conflict do nothing;
insert into public.tags (slug, name, category) values ('memory', 'memory', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-memory' and tags.slug = 'memory' on conflict do nothing;
insert into public.tags (slug, name, category) values ('knowledge', 'knowledge', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-memory' and tags.slug = 'knowledge' on conflict do nothing;
insert into public.tags (slug, name, category) values ('graph', 'graph', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'mcp-server-memory' and tags.slug = 'graph' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('github-copilot-coding-agent', 'GitHub Copilot Coding Agent', 'github_plugin', 'GitHub-native AI coding workflow for assigning implementation work, iterating on pull requests, and accelerating repository tasks.', array['GitHub Copilot', 'Codex']::text[], 'Enable GitHub Copilot in the target organization or repository', array['Issue-to-PR workflows', 'repository automation', 'code suggestions']::text[], 'medium', 89, 83, 'https://github.com/features/copilot', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-copilot-coding-agent' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('copilot', 'copilot', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-copilot-coding-agent' and tags.slug = 'copilot' on conflict do nothing;
insert into public.tags (slug, name, category) values ('coding-agent', 'coding-agent', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-copilot-coding-agent' and tags.slug = 'coding-agent' on conflict do nothing;
insert into public.tags (slug, name, category) values ('pull-request', 'pull-request', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-copilot-coding-agent' and tags.slug = 'pull-request' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('github-actions-ai-review-workflow', 'GitHub Actions AI Review Workflow', 'github_plugin', 'Template workflow pattern for running AI-assisted checks, summaries, or review helpers inside GitHub Actions.', array['Codex', 'GitHub Copilot']::text[], 'Add a GitHub Actions workflow with the chosen AI provider credentials', array['PR summaries', 'lint explanations', 'release notes']::text[], 'medium', 74, 78, 'https://github.com/features/actions', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-actions-ai-review-workflow' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('actions', 'actions', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-actions-ai-review-workflow' and tags.slug = 'actions' on conflict do nothing;
insert into public.tags (slug, name, category) values ('review', 'review', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-actions-ai-review-workflow' and tags.slug = 'review' on conflict do nothing;
insert into public.tags (slug, name, category) values ('automation', 'automation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'github-actions-ai-review-workflow' and tags.slug = 'automation' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('openai-codex-github-connector', 'OpenAI Codex GitHub Connector', 'github_plugin', 'Connects Codex work with GitHub repositories so agents can inspect branches, issues, pull requests, and review feedback.', array['Codex']::text[], 'Install and authorize the GitHub connector in Codex', array['Repository context', 'PR fixes', 'branch handoff']::text[], 'medium', 88, 90, 'https://github.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'openai-codex-github-connector' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('codex', 'codex', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'openai-codex-github-connector' and tags.slug = 'codex' on conflict do nothing;
insert into public.tags (slug, name, category) values ('connector', 'connector', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'openai-codex-github-connector' and tags.slug = 'connector' on conflict do nothing;
insert into public.tags (slug, name, category) values ('repository', 'repository', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'openai-codex-github-connector' and tags.slug = 'repository' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('coderabbit-github-app', 'CodeRabbit GitHub App', 'github_plugin', 'AI pull request review assistant that comments on code changes and highlights possible issues in GitHub PRs.', array['GitHub', 'Codex']::text[], 'Install CodeRabbit from the GitHub Marketplace', array['PR review', 'code quality', 'review summaries']::text[], 'medium', 78, 74, 'https://github.com/marketplace/coderabbitai', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'coderabbit-github-app' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('review', 'review', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'coderabbit-github-app' and tags.slug = 'review' on conflict do nothing;
insert into public.tags (slug, name, category) values ('ai-review', 'ai-review', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'coderabbit-github-app' and tags.slug = 'ai-review' on conflict do nothing;
insert into public.tags (slug, name, category) values ('quality', 'quality', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'coderabbit-github-app' and tags.slug = 'quality' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('sweep-ai', 'Sweep AI', 'github_plugin', 'GitHub issue-to-code assistant that can propose changes from issue descriptions and repository context.', array['GitHub', 'Codex']::text[], 'Install Sweep AI GitHub app', array['Issue implementation', 'small code changes', 'repository tasks']::text[], 'medium', 70, 70, 'https://github.com/sweepai/sweep', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('github', 'github', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'sweep-ai' and tags.slug = 'github' on conflict do nothing;
insert into public.tags (slug, name, category) values ('issues', 'issues', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'sweep-ai' and tags.slug = 'issues' on conflict do nothing;
insert into public.tags (slug, name, category) values ('automation', 'automation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'sweep-ai' and tags.slug = 'automation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('agent', 'agent', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'sweep-ai' and tags.slug = 'agent' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('shadcn-ui', 'shadcn/ui', 'ui_component', 'Copy-paste component system built on Radix primitives and Tailwind CSS, ideal for controllable SaaS interfaces.', array['Codex', 'v0', 'Cursor']::text[], 'npx shadcn@latest init', array['Design systems', 'dashboards', 'forms', 'SaaS apps']::text[], 'low', 95, 96, 'https://github.com/shadcn-ui/ui', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'shadcn-ui' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('shadcn', 'shadcn', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'shadcn-ui' and tags.slug = 'shadcn' on conflict do nothing;
insert into public.tags (slug, name, category) values ('radix', 'radix', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'shadcn-ui' and tags.slug = 'radix' on conflict do nothing;
insert into public.tags (slug, name, category) values ('tailwind', 'tailwind', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'shadcn-ui' and tags.slug = 'tailwind' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('aceternity-ui', 'Aceternity UI', 'ui_component', 'Modern Tailwind and Framer Motion inspired component collection for premium landing pages and AI SaaS surfaces.', array['Codex', 'v0', 'Cursor']::text[], 'Copy selected components from Aceternity UI into the app', array['Hero sections', 'animated cards', 'visual polish']::text[], 'medium', 82, 86, 'https://ui.aceternity.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'aceternity-ui' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('aceternity', 'aceternity', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'aceternity-ui' and tags.slug = 'aceternity' on conflict do nothing;
insert into public.tags (slug, name, category) values ('tailwind', 'tailwind', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'aceternity-ui' and tags.slug = 'tailwind' on conflict do nothing;
insert into public.tags (slug, name, category) values ('motion', 'motion', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'aceternity-ui' and tags.slug = 'motion' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('react-bits', 'React Bits', 'ui_component', 'Animated React component patterns for high-impact interactions, micro animations, backgrounds, and UI flourishes.', array['Codex', 'v0', 'Cursor']::text[], 'Copy selected React Bits snippets into local components', array['Micro interactions', 'animated backgrounds', 'AI product polish']::text[], 'medium', 76, 82, 'https://www.reactbits.dev', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'react-bits' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('react', 'react', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'react-bits' and tags.slug = 'react' on conflict do nothing;
insert into public.tags (slug, name, category) values ('animation', 'animation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'react-bits' and tags.slug = 'animation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('components', 'components', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'react-bits' and tags.slug = 'components' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('motion', 'Motion', 'ui_component', 'Animation library for React and web interfaces, useful for smooth card hover states, transitions, and layout motion.', array['Codex', 'v0', 'Cursor']::text[], 'npm install motion', array['Hover animation', 'page transitions', 'interactive UI polish']::text[], 'low', 89, 88, 'https://github.com/motiondivision/motion', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'motion' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('motion', 'motion', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'motion' and tags.slug = 'motion' on conflict do nothing;
insert into public.tags (slug, name, category) values ('animation', 'animation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'motion' and tags.slug = 'animation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('react', 'react', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'motion' and tags.slug = 'react' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('magic-ui', 'Magic UI', 'ui_component', 'Animated Tailwind component patterns that pair well with shadcn/ui for modern AI product interfaces.', array['Codex', 'v0', 'Cursor']::text[], 'Copy selected Magic UI components into local components', array['Animated cards', 'gradients', 'AI SaaS decoration']::text[], 'medium', 80, 79, 'https://magicui.design', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'magic-ui' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('tailwind', 'tailwind', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'magic-ui' and tags.slug = 'tailwind' on conflict do nothing;
insert into public.tags (slug, name, category) values ('animation', 'animation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'magic-ui' and tags.slug = 'animation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('components', 'components', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'magic-ui' and tags.slug = 'components' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('origin-ui', 'Origin UI', 'ui_component', 'Composable Tailwind and shadcn-oriented UI examples for product dashboards, forms, controls, and dense interfaces.', array['Codex', 'v0', 'Cursor']::text[], 'Copy selected Origin UI components into local components', array['Dashboards', 'forms', 'settings screens']::text[], 'low', 81, 80, 'https://originui.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui', 'ui', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'origin-ui' and tags.slug = 'ui' on conflict do nothing;
insert into public.tags (slug, name, category) values ('shadcn', 'shadcn', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'origin-ui' and tags.slug = 'shadcn' on conflict do nothing;
insert into public.tags (slug, name, category) values ('tailwind', 'tailwind', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'origin-ui' and tags.slug = 'tailwind' on conflict do nothing;
insert into public.tags (slug, name, category) values ('components', 'components', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'origin-ui' and tags.slug = 'components' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('v0-by-vercel', 'v0 by Vercel', 'ui_component', 'AI UI generation tool that produces React, Tailwind, and shadcn/ui oriented interface drafts.', array['v0', 'Codex']::text[], 'Generate UI in v0, then import code into the Next.js app', array['UI prototyping', 'component drafts', 'design exploration']::text[], 'medium', 86, 84, 'https://v0.app', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('ui-generation', 'ui-generation', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'v0-by-vercel' and tags.slug = 'ui-generation' on conflict do nothing;
insert into public.tags (slug, name, category) values ('v0', 'v0', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'v0-by-vercel' and tags.slug = 'v0' on conflict do nothing;
insert into public.tags (slug, name, category) values ('vercel', 'vercel', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'v0-by-vercel' and tags.slug = 'vercel' on conflict do nothing;
insert into public.tags (slug, name, category) values ('shadcn', 'shadcn', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'v0-by-vercel' and tags.slug = 'shadcn' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('next-js-supabase-starter', 'Next.js Supabase Starter', 'template_repo', 'Starter pattern for building Next.js apps with Supabase auth, database access, and environment configuration.', array['Codex', 'Cursor']::text[], 'Use the template or copy the Supabase client structure', array['SaaS MVP', 'auth setup', 'database-backed apps']::text[], 'low', 86, 88, 'https://github.com/vercel/next.js/tree/canary/examples/with-supabase', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'next-js-supabase-starter' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('nextjs', 'nextjs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'next-js-supabase-starter' and tags.slug = 'nextjs' on conflict do nothing;
insert into public.tags (slug, name, category) values ('supabase', 'supabase', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'next-js-supabase-starter' and tags.slug = 'supabase' on conflict do nothing;
insert into public.tags (slug, name, category) values ('auth', 'auth', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'next-js-supabase-starter' and tags.slug = 'auth' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('create-t3-app', 'Create T3 App', 'template_repo', 'Opinionated full-stack TypeScript starter that can help teams compare Next.js app architecture choices.', array['Codex', 'Cursor']::text[], 'npm create t3-app@latest', array['TypeScript web apps', 'full-stack scaffolding', 'architecture comparison']::text[], 'medium', 84, 70, 'https://github.com/t3-oss/create-t3-app', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'create-t3-app' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('nextjs', 'nextjs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'create-t3-app' and tags.slug = 'nextjs' on conflict do nothing;
insert into public.tags (slug, name, category) values ('typescript', 'typescript', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'create-t3-app' and tags.slug = 'typescript' on conflict do nothing;
insert into public.tags (slug, name, category) values ('fullstack', 'fullstack', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'create-t3-app' and tags.slug = 'fullstack' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('taxonomy-template-for-agent-resources', 'Taxonomy Template for Agent Resources', 'template_repo', 'Internal seed template for normalizing skills, MCP servers, plugins, UI libraries, and templates into one resource catalog.', array['Codex']::text[], 'Copy the seed data model into data/seed-resources.ts', array['Resource catalog', 'recommendation engine', 'admin import']::text[], 'low', 83, 94, 'https://github.com', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'taxonomy-template-for-agent-resources' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('taxonomy', 'taxonomy', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'taxonomy-template-for-agent-resources' and tags.slug = 'taxonomy' on conflict do nothing;
insert into public.tags (slug, name, category) values ('agent', 'agent', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'taxonomy-template-for-agent-resources' and tags.slug = 'agent' on conflict do nothing;
insert into public.tags (slug, name, category) values ('catalog', 'catalog', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'taxonomy-template-for-agent-resources' and tags.slug = 'catalog' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('ai-saas-dashboard-template', 'AI SaaS Dashboard Template', 'template_repo', 'Generic Next.js dashboard template direction for dense SaaS interfaces with cards, tables, filters, and analytics panels.', array['Codex', 'v0', 'Cursor']::text[], 'Use as a design reference and implement locally with shadcn/ui', array['Resource library', 'admin console', 'analytics dashboard']::text[], 'medium', 72, 87, 'https://vercel.com/templates', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'ai-saas-dashboard-template' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('dashboard', 'dashboard', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'ai-saas-dashboard-template' and tags.slug = 'dashboard' on conflict do nothing;
insert into public.tags (slug, name, category) values ('saas', 'saas', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'ai-saas-dashboard-template' and tags.slug = 'saas' on conflict do nothing;
insert into public.tags (slug, name, category) values ('nextjs', 'nextjs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'ai-saas-dashboard-template' and tags.slug = 'nextjs' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('supabase-pgvector-starter', 'Supabase pgvector Starter', 'template_repo', 'Reference architecture for storing embeddings in Postgres with pgvector and querying similarity from a product app.', array['Codex', 'Cursor']::text[], 'Enable pgvector and apply the schema pattern to Supabase', array['Semantic search', 'recommendation retrieval', 'embedding storage']::text[], 'medium', 82, 91, 'https://supabase.com/docs/guides/ai', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'supabase-pgvector-starter' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('supabase', 'supabase', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'supabase-pgvector-starter' and tags.slug = 'supabase' on conflict do nothing;
insert into public.tags (slug, name, category) values ('pgvector', 'pgvector', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'supabase-pgvector-starter' and tags.slug = 'pgvector' on conflict do nothing;
insert into public.tags (slug, name, category) values ('embeddings', 'embeddings', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'supabase-pgvector-starter' and tags.slug = 'embeddings' on conflict do nothing;

insert into public.resources (slug, name, type, description, supported_agents, install_command, use_cases, risk_level, trust_score, fit_score, repo_url, source, last_updated)
values ('vercel-ai-sdk-starter', 'Vercel AI SDK Starter', 'template_repo', 'Template direction for adding AI chat, structured generation, and model-provider abstractions to Next.js apps.', array['Codex', 'v0', 'Cursor']::text[], 'npm install ai', array['AI chat', 'structured generation', 'recommendation assistant']::text[], 'medium', 85, 82, 'https://github.com/vercel/ai', 'curated_seed', '2026-07-09')
on conflict (slug) do update set name = excluded.name, type = excluded.type, description = excluded.description, supported_agents = excluded.supported_agents, install_command = excluded.install_command, use_cases = excluded.use_cases, risk_level = excluded.risk_level, trust_score = excluded.trust_score, fit_score = excluded.fit_score, repo_url = excluded.repo_url, source = excluded.source, last_updated = excluded.last_updated;
insert into public.tags (slug, name, category) values ('template', 'template', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'vercel-ai-sdk-starter' and tags.slug = 'template' on conflict do nothing;
insert into public.tags (slug, name, category) values ('ai-sdk', 'ai-sdk', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'vercel-ai-sdk-starter' and tags.slug = 'ai-sdk' on conflict do nothing;
insert into public.tags (slug, name, category) values ('vercel', 'vercel', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'vercel-ai-sdk-starter' and tags.slug = 'vercel' on conflict do nothing;
insert into public.tags (slug, name, category) values ('nextjs', 'nextjs', 'seed') on conflict (slug) do update set name = excluded.name;
insert into public.resource_tags (resource_id, tag_id) select resources.id, tags.id from public.resources, public.tags where resources.slug = 'vercel-ai-sdk-starter' and tags.slug = 'nextjs' on conflict do nothing;

commit;